name: "Build a Forge project"

on:
  workflow_call:
    inputs:
      cache-path:
        default: |
          cache
          node_modules
          out
          out-optimized
        required: false
        type: "string"

      save-cache:
        default: true
        required: false
        type: boolean

      store-artifacts:
        default: true
        required: false
        type: boolean

jobs:
  forge-build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"
        with:
          submodules: recursive

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"

      - name: "Show the Forge config"
        run: "forge config"

      - name: "Install Forge Libraries"
        run: "forge install"

      - name: "Build the contracts"
        run: "forge build"

      - name: "Prepare the contract artifacts"
        if: ${{ inputs.store-artifacts }}
        run: "./shell/prepare-artifacts.sh"

      - name: "Store the contract artifacts in CI"
        if: ${{ inputs.store-artifacts }}
        uses: "actions/upload-artifact@v3"
        with:
          name: "contract-artifacts"
          path: "artifacts"

      - name: "Add summary"
        run: |
          echo "## Build result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
